### ISSUE TITLE
`wp_slashes` is being done in Distributor Core

### ISSUE THREAD

**Issue by jmslbam** [burovoordeboeg/distributor-meta-data#1]
@jstreuper Ik zie dat core nu met de laatste versie ook `wp_slashes` uitvoert voordat deze de post insert, dus misschien dienen wij dat uit deze plugin te halen.

Issue: https://github.com/10up/distributor/issues/889
PR: https://github.com/10up/distributor/pull/890

Voor het mooie even nakijken of de boel nog netjes werkt of dat `wp_slashes` dubbel uitgevoerd wordt, terwijl dat maar 1 x hoeft.

Wil je dat ik dat inplan om na te lopen?

**Comment by jstreuper** [comment]
Hi,

Graag, als dit problemen veroorzaakt ben ik dat liever voor &#128522;


Met vriendelijke groet,
Justin Streuper

**Comment by jmslbam** [comment]
Okidokie, ik neem het mee, geniet van de time-off!

**Comment by jmslbam** [comment]
Ok, done, check is ingebouwd. 

En let aub op met updaten, want er zit een dikke bug in de huidige / laatste versie 1.7.0 die heel het pushen van de CPT kaput macht. De 1.7.1 is net 2 uurtjes geleden aangemaakt en uitgerold.... maar ik zat net tegen 1.7.0 aan te testen dat  in die time-span van 10 dagen dat die online heeft gestaan... 

Dus, 1.7.1 is ook getest en die werkt https://github.com/10up/distributor/releases/tag/1.7.1

**Comment by jmslbam** [comment]
En ik trok trouwens de staging binnen via WP DB Migrator en daar zat nog een hele oude Distributor op.... dus ik zat daar ook nog even mee te vechten. Ik update daar de boel ook zodat Distributor en de Meta package bij zijn. (sorry voor de spam)

**Comment by jstreuper** [comment]
Oké ik heb de pull-request gemerged, moeten we nu verder nog iets doen?

**Comment by jmslbam** [comment]
Ik heb de release aangemaakt en een zip erbij geupload die bij elke project geupload kan worden als nieuwe versie.

https://github.com/burovoordeboeg/distributor-meta-data/releases/download/0.3.3/distributor-meta-data.zip

Dan kan Distributor geupdate worden naar iig 1.7.1.

Ik kan dat inplannen voor a.s. maandag als je wilt. 

Ik bel sowieso morgen even voor de lunch +/- 12:00
